ALTER TABLE server_metrics
    ADD COLUMN IF NOT EXISTS cpu_cores INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE server_metric_samples
    ADD COLUMN IF NOT EXISTS cpu_cores INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0;
